### PR TITLE
Guard against usize overflows/underflows and raw pointer undefined behavior

### LINKED ISSUE #49: Undefined Behavior with dict and pointer arithmetic
The add method on  https://doc.rust-lang.org/std/primitive.pointer.html#safety-5 mentions that:

"Both the starting and resulting pointer must be either in bounds or one byte past the end of the same [allocated object](https://doc.rust-lang.org/std/ptr/index.html#allocated-object)."

But there are several places, where pointer arithmetic is used to move outside an allocated object.

`MIRIFLAGS="-Zmiri-disable-isolation -Zmiri-disable-stacked-borrows" cargo +nightly miri test --no-default-features` fails for dict tests currently

@arthurprs

### PR DESCRIPTION
**Pull request by arthurprs**
The main change is to change patterns like `current_position + something > max_position` to `max_position - current_position < something`, which is overflow safe. Closes #49

### CODE REVIEW

File: src/block/compress.rs [hunk 1]
```diff
@@ -177,7 +177,7 @@ fn count_same_bytes(input: &[u8], cur: &mut usize, source: &[u8], candidate: usi
     // compare 4 bytes block
     #[cfg(target_pointer_width = "64")]
     {
-        if *cur + 4 <= input_end {
```
Comment (PSeitz) [inline src/block/compress.rs:180]: cur and input_end are usize, they are unaffected by the issue

Comment (arthurprs) [reply src/block/compress.rs:180]: Right, but since we're dealing with under/overflow style problems I thought it would be best to fix all of them. Theoretically an allocation at the end of the address space could lead to *cur + 4 to overflow.

**Comment by PSeitz** [comment]
Awesome, thanks for the PR!
